# ==============================
# SERVER
# ==============================
server.port=8080

# ==============================
# MONGODB CONFIG (Railway / Atlas)
# ==============================
spring.data.mongodb.uri=mongodb+srv://indhumathirsj_db_user:75AWrnbYFotmSdv7@cluster0.vgipjfv.mongodb.net/carMongoDB
spring.data.mongodb.database=carMongoDB
spring.main.allow-bean-definition-overriding=true


